version: "3"

services:
  mysql_serve:
    image: mysql:5.6.42
    container_name: db_acred_divisiones
    ports:
      - 33060:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: kevin123
      MYSQL_DATABASE: acred_divisiones2
      MYSQL_ROOT_PASSWORD: kevin123
  mongo_serve:
    image: mongo
    container_name: db_mongo_acred_divisiones
    ports:
      - 27018:27017
  composer_acred:
    image: composer:latest
    container_name: composer_acred_divisiones
    command: composer install --ignore-platform-reqs
    volumes:
      - /var/www/html/acred_divisiones:/app
  web:
    build: .
    container_name: web_acred_divisiones
    ports:
      - 8000:80
    volumes:
      - /var/www/html/acred_divisiones:/opt/data
    links:
      - mysql_serve
      - mongo_serve
